use crate::ast::JavaSyntaxKind;

pub(super) fn token_display(kind: JavaSyntaxKind) -> String {
    use JavaSyntaxKind::*;
    match kind {
        AbstractKw => "`abstract`",
        AssertKw => "`assert`",
        BooleanKw => "`boolean`",
        BreakKw => "`break`",
        ByteKw => "`byte`",
        CaseKw => "`case`",
        CatchKw => "`catch`",
        CharKw => "`char`",
        ClassKw => "`class`",
        ContinueKw => "`continue`",
        DefaultKw => "`default`",
        DoKw => "`do`",
        DoubleKw => "`double`",
        ElseKw => "`else`",
        EnumKw => "`enum`",
        ExtendsKw => "`extends`",
        FinalKw => "`final`",
        FinallyKw => "`finally`",
        FloatKw => "`float`",
        ForKw => "`for`",
        IfKw => "`if`",
        ImplementsKw => "`implements`",
        ImportKw => "`import`",
        InstanceofKw => "`instanceof`",
        IntKw => "`int`",
        InterfaceKw => "`interface`",
        LongKw => "`long`",
        NativeKw => "`native`",
        NewKw => "`new`",
        PackageKw => "`package`",
        PrivateKw => "`private`",
        ProtectedKw => "`protected`",
        PublicKw => "`public`",
        ReturnKw => "`return`",
        ShortKw => "`short`",
        StaticKw => "`static`",
        StrictfpKw => "`strictfp`",
        SuperKw => "`super`",
        SwitchKw => "`switch`",
        SynchronizedKw => "`synchronized`",
        ThisKw => "`this`",
        ThrowKw => "`throw`",
        ThrowsKw => "`throws`",
        TransientKw => "`transient`",
        TryKw => "`try`",
        VoidKw => "`void`",
        VolatileKw => "`volatile`",
        WhileKw => "`while`",
        YieldKw => "`yield`",
        RecordKw => "`record`",
        SealedKw => "`sealed`",
        NonSealedKw => "`non-sealed`",
        PermitsKw => "`permits`",
        VarKw => "`var`",
        IntLiteral => "integer literal",
        LongLiteral => "long literal",
        FloatLiteral => "float literal",
        DoubleLiteral => "double literal",
        CharLiteral => "character literal",
        StringLiteral => "string literal",
        TextBlockLiteral => "text block literal",
        TrueKw => "`true`",
        FalseKw => "`false`",
        NullKw => "`null`",
        Ident => "identifier",
        LBrace => "`{`",
        RBrace => "`}`",
        LBrack => "`[`",
        RBrack => "`]`",
        LParen => "`(`",
        RParen => "`)`",
        Semi => "`;`",
        Comma => "`,`",
        Dot => "`.`",
        Ellipsis => "`...`",
        At => "`@`",
        ColonColon => "`::`",
        Arrow => "`->`",
        Eq => "`=`",
        Gt => "`>`",
        Lt => "`<`",
        Bang => "`!`",
        Tilde => "`~`",
        Question => "`?`",
        Colon => "`:`",
        EqEq => "`==`",
        Le => "`<=`",
        Ge => "`>=`",
        Neq => "`!=`",
        Inc => "`++`",
        Dec => "`--`",
        AmpAmp => "`&&`",
        PipePipe => "`||`",
        Plus => "`+`",
        Minus => "`-`",
        Star => "`*`",
        Slash => "`/`",
        Amp => "`&`",
        Pipe => "`|`",
        Caret => "`^`",
        Percent => "`%`",
        LtLt => "`<<`",
        GtGt => "`>>`",
        GtGtGt => "`>>>`",
        PlusEq => "`+=`",
        MinusEq => "`-=`",
        StarEq => "`*=`",
        SlashEq => "`/=`",
        AmpEq => "`&=`",
        PipeEq => "`|=`",
        CaretEq => "`^=`",
        PercentEq => "`%=`",
        LtLtEq => "`<<=`",
        GtGtEq => "`>>=`",
        GtGtGtEq => "`>>>=`",
        Underscore => "`_`",
        Error => "end of input",
        _ => "syntax",
    }
    .to_string()
}
