use logos::Logos;

#[derive(Logos, Debug, Clone, Copy, PartialEq, Eq)]
#[logos(skip r"[ \t\r\n\f]+")]
#[logos(skip(r"//[^\n]*", allow_greedy = true))]
#[logos(skip(r"/\*[\s\S]*?\*/", allow_greedy = true))]
pub enum TextualToken {
    #[token("abstract")] Abstract,
    #[token("assert")] Assert,
    #[token("boolean")] Boolean,
    #[token("break")] Break,
    #[token("byte")] Byte,
    #[token("case")] Case,
    #[token("catch")] Catch,
    #[token("char")] Char,
    #[token("class")] Class,
    #[token("continue")] Continue,
    #[token("default")] Default,
    #[token("do")] Do,
    #[token("double")] Double,
    #[token("else")] Else,
    #[token("enum")] Enum,
    #[token("extends")] Extends,
    #[token("final")] Final,
    #[token("finally")] Finally,
    #[token("float")] Float,
    #[token("for")] For,
    #[token("if")] If,
    #[token("implements")] Implements,
    #[token("import")] Import,
    #[token("instanceof")] Instanceof,
    #[token("int")] Int,
    #[token("interface")] Interface,
    #[token("long")] Long,
    #[token("native")] Native,
    #[token("new")] New,
    #[token("package")] Package,
    #[token("private")] Private,
    #[token("protected")] Protected,
    #[token("public")] Public,
    #[token("return")] Return,
    #[token("short")] Short,
    #[token("static")] Static,
    #[token("strictfp")] Strictfp,
    #[token("super")] Super,
    #[token("switch")] Switch,
    #[token("synchronized")] Synchronized,
    #[token("this")] This,
    #[token("throw")] Throw,
    #[token("throws")] Throws,
    #[token("transient")] Transient,
    #[token("try")] Try,
    #[token("void")] Void,
    #[token("volatile")] Volatile,
    #[token("while")] While,
    #[token("yield")] Yield,
    #[token("record")] Record,
    #[token("sealed")] Sealed,
    #[token("non-sealed")] NonSealed,
    #[token("permits")] Permits,
    #[token("var")] Var,

    #[regex(r"0[xX][0-9a-fA-F_]+[lL]?", priority = 3)] HexLiteral,
    #[regex(r"0[bB][01_]+[lL]?", priority = 3)] BinLiteral,
    #[regex(r"[0-9][0-9_]*[lL]", priority = 4)] LongLiteral,
    #[regex(r"[0-9][0-9_]*", priority = 2)] IntLiteral,
    #[regex(r"[0-9][0-9_]*\.[0-9_]*([eE][+-]?[0-9_]+)?[fFdD]?", priority = 5)] FloatLiteral,
    #[regex(r"[0-9][0-9_]*[eE][+-]?[0-9_]+[fFdD]?", priority = 5)] FloatLiteralExp,
    #[regex(r"\.[0-9][0-9_]*([eE][+-]?[0-9_]+)?[fFdD]?", priority = 6)] FloatLiteralDot,
    #[regex(r"[0-9][0-9_]*[fFdD]", priority = 4)] FloatLiteralSuffix,
    #[regex(r"'([^'\\\r\n]|\\.)*'")] CharLiteral,
    #[regex(r#""([^"\\\r\n]|\\.)*""#)] StringLiteral,
    #[regex(r#""""[ \t]*\r?\n[\s\S]*?"""""#)] TextBlock,

    #[token("true")] True,
    #[token("false")] False,
    #[token("null")] Null,

    #[regex(r"[a-zA-Z_$][a-zA-Z0-9_$]*", priority = 1)] Ident,

    #[token("{")] LBrace,
    #[token("}")] RBrace,
    #[token("[")] LBrack,
    #[token("]")] RBrack,
    #[token("(")] LParen,
    #[token(")")] RParen,
    #[token(";")] Semi,
    #[token(",")] Comma,
    #[token(".")] Dot,
    #[token("...")] Ellipsis,
    #[token("@")] At,
    #[token("::")] ColonColon,
    #[token("->")] Arrow,

    #[token("=")] Eq,
    #[token(">")] Gt,
    #[token("<")] Lt,
    #[token("!")] Bang,
    #[token("~")] Tilde,
    #[token("?")] Question,
    #[token(":")] Colon,
    #[token("==")] EqEq,
    #[token("<=")] Le,
    #[token(">=")] Ge,
    #[token("!=")] Neq,
    #[token("++")] Inc,
    #[token("--")] Dec,
    #[token("&&")] AmpAmp,
    #[token("||")] PipePipe,
    #[token("+")] Plus,
    #[token("-")] Minus,
    #[token("*")] Star,
    #[token("/")] Slash,
    #[token("&")] Amp,
    #[token("|")] Pipe,
    #[token("^")] Caret,
    #[token("%")] Percent,
    #[token("<<")] LtLt,
    #[token(">>")] GtGt,
    #[token(">>>")] GtGtGt,
    #[token("+=")] PlusEq,
    #[token("-=")] MinusEq,
    #[token("*=")] StarEq,
    #[token("/=")] SlashEq,
    #[token("&=")] AmpEq,
    #[token("|=")] PipeEq,
    #[token("^=")] CaretEq,
    #[token("%=")] PercentEq,
    #[token("<<=")] LtLtEq,
    #[token(">>=")] GtGtEq,
    #[token(">>>=")] GtGtGtEq,
    #[token("_")] Underscore,
}